import { Project } from './project';

export const PROJECTS: Project[] = [
  {
    id: 1,
    name: 'Od jewels',
    coverPicture: './assets/img/odjewels-cover.jpg',
    deliverables: ['Moodboard',
      'Website', 'architecture',
      'Graphic chart',
      'Templates',
      'Host',
      'Domain name',
      'Integration',
      'Guide to use wordpress'],
    toolsSkills: ['UX/UI principe',
      'Front-end skills',
      'Adobe PS + AI + XD',
      'Hostinger',
      'Woordpress',
      ' Woocommerce (paypal)', '', ''],
    myPosition: 'Only me as UX/UI and front-end',
    duration: 'July 2021 to January 2022',
    overviewText: 'OD.jewels offers Ethical Luxury with a current look, and a desire for innovation! The artist proposes: Handmade - Engagement rings - Ethical jewels in Gold and Silver - Genderless jewels. OD.jewels was born from a dream and a desire to bring together several values to offer an ethical and magical product full of energy. The jewels are not only based on aesthetics, each of them is thought and realized as real little talismans.',
    subTitle1: 'The demand',
    subTitle1Text: 'With an instagram and some sell trough different webplatforme, OD.jewels as a new business, had the desire to grow the brand and having their own webplatforme to manage their sell. The artist call me to help him to achieve that.',
    subTitle2: 'The solution',
    subTitle2Text: 'After meeting the client and identifying their goals, the solution was clear. They needed a branding website where they can manage easily their products online and allow their clients to have a good experience online.',
    tasksTitleSection: 'THE PROCESS',
    tasksTitleSectionText: '',
    tasksSubTitle1: 'Moodboard',
    tasksSubTitle1Text: ' After doing researchs, benchamrk, I created a moodboard to present the branding direction. The moodboard combined fonts, colors, picture to present the atmosphere, ...',
    tasksSubTitle2: 'Information Architecture / Sitemap / Mockup (low fidelity)',
    tasksSubTitle2Text: 'To represente the information hierarchy, navigation and main actions.',
    tasksSubTitle3: 'Mockup (High fidelity) and the responsive integration',
    tasksSubTitle3Text: 'After the validation of the sitemap, IA and low fidelity mock-up, I created the high fidelity mockup of the futur website. And after the validation, I integrated the design in Wordpress. Wordpress as a popular CMS, with woocommerce was the ideal choice for this e-commerce website. I paid attention as the design be responsive.',
    linkProject: 'https://www.odjewels.eu/',
    picture1: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture2: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture3: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture4: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
  },

  {
    id: 2,
    name: 'European Commission',
    coverPicture: './assets/img/ce-cover.jpg',
    deliverables: ['Mockups low and high fidelity',
      'Prototypes in HTML',
      'UX reviews',
      'UX + front-end supports', '', '', '', '', ''],
    toolsSkills: ['UX/UI skills',
    'Front-end skills',
    'Adobe PS + AI + XD',
    'eUi library',
    'Angular',
    'Invision',
    'Jira',
    'Agile (scrum) environement',],
    myPosition: 'UX/UI and front-end consulant in the UX team service at DIGIT',
    duration: '1year July 2020 to October 2021',
    overviewText: 'As a junior consultant for ARHS, I did a mission during more than 1 year at the European Commission as UX/UI and front-end developer at the DIGIT departement of EC “The Directorate-General for Informatics is the Commission department responsible for providing digital services that support other Commission departments and EU institutions in their daily work and that help public administrations in EU member countries work better together.”',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'TASKS',
    tasksTitleSectionText: 'During my mission at the European Commission, I participated in more than 8 different projects. I assisted and collaborated with front-end/backend developers in differents departments’s projects, to improve the design and the UX but also to review and improve the accessibility and UI of existing projects.',
    tasksSubTitle1: 'Review',
    tasksSubTitle1Text: ' Some departements needed the help of the UX team to imrpove the user exeprience in their wabplatfome.. ',
    //The aim of the review is to evaluate the actual website of the Project and identify UX issues and proposed ideas of how to improve the platform for users. We used the Usability Heuristics evaluation.',
    tasksSubTitle2: 'Mockups and Prototypes',
    tasksSubTitle2Text: 'After the UX review, some projects needed to rethink completly. So collaborately with an other UX designer from the UX tem or by myself, we improved the plafome. by using mock-ups to present the new UX design improvement. ',
    //Sometimes, I was supporting new project as UX and Front-end developer. I was supporting other team to improve, create and present new pages. Indeed, the UX team was called at the start of some projects to assure an accessibility and user friendly platfom. the process.
    //Me as UX and front-end developer, I was called after the research, audit that my collegueas from UX team did to create and present the design with mockups and animated prototypes.  In some case, the project needed an HTML prototype, that I realised. 
    //Once the validation of the design was done, the integration started.',
    tasksSubTitle3: 'Integration',
    tasksSubTitle3Text: 'After the validation of the mockups and prototypes, it was the time to integrate the design. And as front-end developer, I supported and assured the good practices of the css and html implemantation during the integration. I worked with other front-end and back-end devolper to achieve that.',
    linkProject: 'https://www.postingdeclaration.eu/landing',
    picture1: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture2: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture3: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture4: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
  },
  {
    id: 4,
    name: 'Logos challenge',
    coverPicture: './assets/img/logo-challenge-cover.jpg',
    deliverables: ['Mockups low and high fidelity',
      'Prototypes in HTML',
      'UX reviews',
      'UX + front-end supports', '', '', '', '', ''],
    toolsSkills: ['UX/UI skills',
    'Front-end skills',
    'Adobe PS + AI + XD',
    'eUi library',
    'Angular',
    'Invision',
    'Jira',
    'Agile (scrum) environement',],
    myPosition: 'UX/UI and front-end consulant in the UX team service at DIGIT',
    duration: '1year July 2020 to October 2021',
    overviewText: 'As a junior consultant for ARHS, I did a mission during more than 1 year at the European Commission as UX/UI and front-end developer at the DIGIT departement of EC “The Directorate-General for Informatics is the Commission department responsible for providing digital services that support other Commission departments and EU institutions in their daily work and that help public administrations in EU member countries work better together.”',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'TASKS',
    tasksTitleSectionText: 'During my mission at the European Commission, I participated in more than 8 different projects. I assisted and collaborated with front-end/backend developers in differents departments’s projects, to improve the design and the UX but also to review and improve the accessibility and UI of existing projects.',
    tasksSubTitle1: 'Review',
    tasksSubTitle1Text: ' Some departements needed the help of the UX team to imrpove the user exeprience in their wabplatfome.. ',
    //The aim of the review is to evaluate the actual website of the Project and identify UX issues and proposed ideas of how to improve the platform for users. We used the Usability Heuristics evaluation.',
    tasksSubTitle2: 'Mockups and Prototypes',
    tasksSubTitle2Text: 'After the UX review, some projects needed to rethink completly. So collaborately with an other UX designer from the UX tem or by myself, we improved the plafome. by using mock-ups to present the new UX design improvement. ',
    //Sometimes, I was supporting new project as UX and Front-end developer. I was supporting other team to improve, create and present new pages. Indeed, the UX team was called at the start of some projects to assure an accessibility and user friendly platfom. the process.
    //Me as UX and front-end developer, I was called after the research, audit that my collegueas from UX team did to create and present the design with mockups and animated prototypes.  In some case, the project needed an HTML prototype, that I realised. 
    //Once the validation of the design was done, the integration started.',
    tasksSubTitle3: 'Integration',
    tasksSubTitle3Text: 'After the validation of the mockups and prototypes, it was the time to integrate the design. And as front-end developer, I supported and assured the good practices of the css and html implemantation during the integration. I worked with other front-end and back-end devolper to achieve that.',
    linkProject: 'https://www.postingdeclaration.eu/landing',
    picture1: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture2: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture3: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture4: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
  },

  {
    id: 6,
    name: 'Sixtines',
    coverPicture: './assets/img/sixtines-cover.jpg',
    deliverables: ['Mockups low and high fidelity',
      'Prototypes in HTML',
      'UX reviews',
      'UX + front-end supports', '', '', '', '', ''],
    toolsSkills: ['UX/UI skills',
    'Front-end skills',
    'Adobe PS + AI + XD',
    'eUi library',
    'Angular',
    'Invision',
    'Jira',
    'Agile (scrum) environement',],
    myPosition: 'UX/UI and front-end consulant in the UX team service at DIGIT',
    duration: '1year July 2020 to October 2021',
    overviewText: 'As a junior consultant for ARHS, I did a mission during more than 1 year at the European Commission as UX/UI and front-end developer at the DIGIT departement of EC “The Directorate-General for Informatics is the Commission department responsible for providing digital services that support other Commission departments and EU institutions in their daily work and that help public administrations in EU member countries work better together.”',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'TASKS',
    tasksTitleSectionText: 'During my mission at the European Commission, I participated in more than 8 different projects. I assisted and collaborated with front-end/backend developers in differents departments’s projects, to improve the design and the UX but also to review and improve the accessibility and UI of existing projects.',
    tasksSubTitle1: 'Review',
    tasksSubTitle1Text: ' Some departements needed the help of the UX team to imrpove the user exeprience in their wabplatfome.. ',
    //The aim of the review is to evaluate the actual website of the Project and identify UX issues and proposed ideas of how to improve the platform for users. We used the Usability Heuristics evaluation.',
    tasksSubTitle2: 'Mockups and Prototypes',
    tasksSubTitle2Text: 'After the UX review, some projects needed to rethink completly. So collaborately with an other UX designer from the UX tem or by myself, we improved the plafome. by using mock-ups to present the new UX design improvement. ',
    //Sometimes, I was supporting new project as UX and Front-end developer. I was supporting other team to improve, create and present new pages. Indeed, the UX team was called at the start of some projects to assure an accessibility and user friendly platfom. the process.
    //Me as UX and front-end developer, I was called after the research, audit that my collegueas from UX team did to create and present the design with mockups and animated prototypes.  In some case, the project needed an HTML prototype, that I realised. 
    //Once the validation of the design was done, the integration started.',
    tasksSubTitle3: 'Integration',
    tasksSubTitle3Text: 'After the validation of the mockups and prototypes, it was the time to integrate the design. And as front-end developer, I supported and assured the good practices of the css and html implemantation during the integration. I worked with other front-end and back-end devolper to achieve that.',
    linkProject: 'https://www.postingdeclaration.eu/landing',
    picture1: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture2: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture3: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture4: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
  },
  {
    id: 7,
    name: 'Feelm',
    coverPicture: './assets/img/feelm-cover.jpg',
    deliverables: ['Mockups low and high fidelity',
      'Prototypes in HTML',
      'UX reviews',
      'UX + front-end supports', '', '', '', '', ''],
    toolsSkills: ['UX/UI skills',
    'Front-end skills',
    'Adobe PS + AI + XD',
    'eUi library',
    'Angular',
    'Invision',
    'Jira',
    'Agile (scrum) environement',],
    myPosition: 'UX/UI and front-end consulant in the UX team service at DIGIT',
    duration: '1year July 2020 to October 2021',
    overviewText: 'As a junior consultant for ARHS, I did a mission during more than 1 year at the European Commission as UX/UI and front-end developer at the DIGIT departement of EC “The Directorate-General for Informatics is the Commission department responsible for providing digital services that support other Commission departments and EU institutions in their daily work and that help public administrations in EU member countries work better together.”',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'TASKS',
    tasksTitleSectionText: 'During my mission at the European Commission, I participated in more than 8 different projects. I assisted and collaborated with front-end/backend developers in differents departments’s projects, to improve the design and the UX but also to review and improve the accessibility and UI of existing projects.',
    tasksSubTitle1: 'Review',
    tasksSubTitle1Text: ' Some departements needed the help of the UX team to imrpove the user exeprience in their wabplatfome.. ',
    //The aim of the review is to evaluate the actual website of the Project and identify UX issues and proposed ideas of how to improve the platform for users. We used the Usability Heuristics evaluation.',
    tasksSubTitle2: 'Mockups and Prototypes',
    tasksSubTitle2Text: 'After the UX review, some projects needed to rethink completly. So collaborately with an other UX designer from the UX tem or by myself, we improved the plafome. by using mock-ups to present the new UX design improvement. ',
    //Sometimes, I was supporting new project as UX and Front-end developer. I was supporting other team to improve, create and present new pages. Indeed, the UX team was called at the start of some projects to assure an accessibility and user friendly platfom. the process.
    //Me as UX and front-end developer, I was called after the research, audit that my collegueas from UX team did to create and present the design with mockups and animated prototypes.  In some case, the project needed an HTML prototype, that I realised. 
    //Once the validation of the design was done, the integration started.',
    tasksSubTitle3: 'Integration',
    tasksSubTitle3Text: 'After the validation of the mockups and prototypes, it was the time to integrate the design. And as front-end developer, I supported and assured the good practices of the css and html implemantation during the integration. I worked with other front-end and back-end devolper to achieve that.',
    linkProject: 'https://www.postingdeclaration.eu/landing',
    picture1: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture2: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture3: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture4: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
  },
  {
    id: 8,
    name: 'Media Animation',
    coverPicture: './assets/img/media-animation-cover.jpg',
    deliverables: ['Mockups low and high fidelity',
      'Prototypes in HTML',
      'UX reviews',
      'UX + front-end supports', '', '', '', '', ''],
    toolsSkills: ['UX/UI skills',
    'Front-end skills',
    'Adobe PS + AI + XD',
    'eUi library',
    'Angular',
    'Invision',
    'Jira',
    'Agile (scrum) environement',],
    myPosition: 'UX/UI and front-end consulant in the UX team service at DIGIT',
    duration: '1year July 2020 to October 2021',
    overviewText: 'As a junior consultant for ARHS, I did a mission during more than 1 year at the European Commission as UX/UI and front-end developer at the DIGIT departement of EC “The Directorate-General for Informatics is the Commission department responsible for providing digital services that support other Commission departments and EU institutions in their daily work and that help public administrations in EU member countries work better together.”',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'TASKS',
    tasksTitleSectionText: 'During my mission at the European Commission, I participated in more than 8 different projects. I assisted and collaborated with front-end/backend developers in differents departments’s projects, to improve the design and the UX but also to review and improve the accessibility and UI of existing projects.',
    tasksSubTitle1: 'Review',
    tasksSubTitle1Text: ' Some departements needed the help of the UX team to imrpove the user exeprience in their wabplatfome.. ',
    //The aim of the review is to evaluate the actual website of the Project and identify UX issues and proposed ideas of how to improve the platform for users. We used the Usability Heuristics evaluation.',
    tasksSubTitle2: 'Mockups and Prototypes',
    tasksSubTitle2Text: 'After the UX review, some projects needed to rethink completly. So collaborately with an other UX designer from the UX tem or by myself, we improved the plafome. by using mock-ups to present the new UX design improvement. ',
    //Sometimes, I was supporting new project as UX and Front-end developer. I was supporting other team to improve, create and present new pages. Indeed, the UX team was called at the start of some projects to assure an accessibility and user friendly platfom. the process.
    //Me as UX and front-end developer, I was called after the research, audit that my collegueas from UX team did to create and present the design with mockups and animated prototypes.  In some case, the project needed an HTML prototype, that I realised. 
    //Once the validation of the design was done, the integration started.',
    tasksSubTitle3: 'Integration',
    tasksSubTitle3Text: 'After the validation of the mockups and prototypes, it was the time to integrate the design. And as front-end developer, I supported and assured the good practices of the css and html implemantation during the integration. I worked with other front-end and back-end devolper to achieve that.',
    linkProject: 'https://www.postingdeclaration.eu/landing',
    picture1: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture2: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture3: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture4: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
  },
  {
    id: 9,
    name: 'RTL Belgium',
    coverPicture: './assets/img/rtl-cover.jpg',
    deliverables: ['Mockups low and high fidelity',
      'Prototypes in HTML',
      'UX reviews',
      'UX + front-end supports', '', '', '', '', ''],
    toolsSkills: ['UX/UI skills',
    'Front-end skills',
    'Adobe PS + AI + XD',
    'eUi library',
    'Angular',
    'Invision',
    'Jira',
    'Agile (scrum) environement',],
    myPosition: 'UX/UI and front-end consulant in the UX team service at DIGIT',
    duration: '1year July 2020 to October 2021',
    overviewText: 'As a junior consultant for ARHS, I did a mission during more than 1 year at the European Commission as UX/UI and front-end developer at the DIGIT departement of EC “The Directorate-General for Informatics is the Commission department responsible for providing digital services that support other Commission departments and EU institutions in their daily work and that help public administrations in EU member countries work better together.”',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'TASKS',
    tasksTitleSectionText: 'During my mission at the European Commission, I participated in more than 8 different projects. I assisted and collaborated with front-end/backend developers in differents departments’s projects, to improve the design and the UX but also to review and improve the accessibility and UI of existing projects.',
    tasksSubTitle1: 'Review',
    tasksSubTitle1Text: ' Some departements needed the help of the UX team to imrpove the user exeprience in their wabplatfome.. ',
    //The aim of the review is to evaluate the actual website of the Project and identify UX issues and proposed ideas of how to improve the platform for users. We used the Usability Heuristics evaluation.',
    tasksSubTitle2: 'Mockups and Prototypes',
    tasksSubTitle2Text: 'After the UX review, some projects needed to rethink completly. So collaborately with an other UX designer from the UX tem or by myself, we improved the plafome. by using mock-ups to present the new UX design improvement. ',
    //Sometimes, I was supporting new project as UX and Front-end developer. I was supporting other team to improve, create and present new pages. Indeed, the UX team was called at the start of some projects to assure an accessibility and user friendly platfom. the process.
    //Me as UX and front-end developer, I was called after the research, audit that my collegueas from UX team did to create and present the design with mockups and animated prototypes.  In some case, the project needed an HTML prototype, that I realised. 
    //Once the validation of the design was done, the integration started.',
    tasksSubTitle3: 'Integration',
    tasksSubTitle3Text: 'After the validation of the mockups and prototypes, it was the time to integrate the design. And as front-end developer, I supported and assured the good practices of the css and html implemantation during the integration. I worked with other front-end and back-end devolper to achieve that.',
    linkProject: 'https://www.postingdeclaration.eu/landing',
    picture1: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture2: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture3: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
    picture4: 'https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg',
  },

];