import { Project } from './project';

export const PROJECTS: Project[] = [
  {
    id: 1,
    name: 'Od jewels',
    coverPicture: './assets/img/odjewels-cover.jpg',
    deliverables: ['Moodboard',
      ' Website', 
      ' architecture',
      ' Graphic chart',
      ' Templates',
      ' Host',
      ' Domain name',
      ' Integration',
      ' Guide to use wordpress'],
    toolsSkills: ['UX/UI principes',
      ' Front-end skills',
      ' Adobe PS + AI + XD',
      ' Hostinger',
      ' Woordpress',
      ' Woocommerce (paypal)', 
      ' FileZilla', 
      'PPT'],
    myPosition: 'Only me as UX/UI and front-end',
    duration: 'July 2021 to January 2022',
    overviewText: 'OD.jewels offers Ethical Luxury with a current look, and a desire for innovation! The artist proposes: Handmade - Engagement rings - Ethical jewels in Gold and Silver - Genderless jewels.' 
    +'OD.jewels was born from a dream and a desire to bring together several values to offer an ethical and magical product full of energy.' 
    +'The jewels are not only based on aesthetics, each of them is thought and realized as real little talismans.',
    subTitle1: 'The demand',
    subTitle1Text: 'With an instagram and some sell trough different webplatforme, OD.jewels as a new business, had the desire to grow the brand and having their own webplatforme to manage their sell. The artist call me to help him to achieve that.',
    subTitle2: 'The solution',
    subTitle2Text: 'After meeting the client and identifying their goals, the solution was clear. They needed a branding website where they can manage easily their products online and allow their clients to have a good experience online.',
    tasksTitleSection: 'THE PROCESS',
    tasksTitleSectionText: '',
    tasksSubTitle1: 'Moodboard',
    tasksSubTitle1Text: ' After doing researchs, benchamrk, I created a moodboard to present the branding direction. The moodboard combined fonts, colors, picture to present the atmosphere, ...',
    tasksSubTitle2: 'Information Architecture / Sitemap / Mockup (low fidelity)',
    tasksSubTitle2Text: 'To represente the information hierarchy, navigation and main actions.',
    tasksSubTitle3: 'Mockup (High fidelity) and the responsive integration',
    tasksSubTitle3Text: 'After the validation of the sitemap, IA and low fidelity mock-up, I created the high fidelity mockup of the futur website. And after the validation, I integrated the design in Wordpress. Wordpress as a popular CMS, with woocommerce was the ideal choice for this e-commerce website. I paid attention as the design be responsive.',
    linkProject: 'https://www.odjewels.eu/',
    picture1: './assets/img/odjewels-moodboard.jpg',
    picture2: './assets/img/odjewels-ia.jpg',
    picture3: './assets/img/odjewels-screens.jpg',
    picture4: '',
  },

  {
    id: 2,
    name: 'European Commission',
    coverPicture: './assets/img/ce-cover.jpg',
    deliverables: ['Mockups low and high fidelity',
      'Prototypes in HTML',
      'UX reviews',
      'UX + front-end supports', 
      'IMI projects', 
      'SCIC', 
      'AGM ', 
      'BRIS', 
      '...'],
    toolsSkills: ['UX/UI skills',
      'Front-end skills',
      'Adobe PS + AI + XD',
      'eUi library',
      'Angular',
      'Invision',
      'Jira',
      'Agile (scrum) environement',],
    myPosition: 'UX/UI and front-end consulant in the UX team service at DIGIT',
    duration: '1year July 2020 to October 2021',
    overviewText: 'As a junior consultant for ARHS, I did a mission during more than 1 year at the European Commission as UX/UI and front-end developer at the DIGIT departement of EC “The Directorate-General for Informatics is the Commission department responsible for providing digital services that support other Commission departments and EU institutions in their daily work and that help public administrations in EU member countries work better together.”',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'TASKS',
    tasksTitleSectionText: 'During my mission at the European Commission, I participated in more than 8 different projects. I assisted and collaborated with front-end/backend developers in differents departments’s projects, to improve the design and the UX but also to review and improve the accessibility and UI of existing projects,...',
    tasksSubTitle1: 'Review',
    tasksSubTitle1Text: ' Some departements needed the help of the UX team to imrpove the user exeprience in their wabplatfome...,'
    +'The aim of the review is to evaluate the actual website of the Project and identify UX issues and proposed ideas of how to improve the platform for users. We used the Usability Heuristics evaluation.',
    tasksSubTitle2: 'Mockups and Prototypes',
    tasksSubTitle2Text: 'After the UX review, some projects needed to rethink completly. So collaborately with an other UX designer from the UX tem or by myself, we improved the plafome. by using mock-ups to present the new UX design improvement.,'
    +'Sometimes, I was supporting new project as UX and Front-end developer. I was supporting other team to improve, create and present new pages. Indeed, the UX team was called at the start of some projects to assure an accessibility and user friendly platfom. the process.'
    +'Me as UX and front-end developer, I was called after the research, audit that my collegueas from UX team did to create and present the design with mockups and animated prototypes.  In some case, the project needed an HTML prototype, that I realised.'
    +'Once the validation of the design was done, the integration started.',
    tasksSubTitle3: 'Integration',
    tasksSubTitle3Text: 'After the validation of the mockups and prototypes, it was the time to integrate the design. And as front-end developer, I supported and assured the good practices of the css and html implemantation during the integration in Angular. I worked with other front-end and back-end devolper to achieve that goal in a Agil environement.',
    linkProject: 'https://www.postingdeclaration.eu/landing',
    picture1: './assets/img/ce-review.jpg',
    picture2: './assets/img/ce-screens.jpg',
    picture3: '',
    picture4: '',
  },
  {
    id: 4,
    name: 'Logos challenge',
    coverPicture: './assets/img/logo-challenge-cover.jpg',
    deliverables: ['logos',
      '',
      '',
      '', '', '', '', '', ''],
    toolsSkills: ['',
      '',
      'Adobe PS + AI',
      '',
      '',
      '',
      '',
      '',],
    myPosition: 'Designer',
    duration: 'some days',
    overviewText: ' Logo Core "will send you a new creative brief to your email each day. Your task will be to design a logo for the client and submit it within a day. It’s a great way to improve as a designer and join the design community!" So, In order to continue to improve my design skills, I participate in tenders for logos',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'What I designed',
    tasksTitleSectionText: '',
    tasksSubTitle1: '',
    tasksSubTitle1Text: '',
    tasksSubTitle2: '',
    tasksSubTitle2Text: '',
    tasksSubTitle3: '',
    tasksSubTitle3Text: '',
    linkProject: 'https://logocore.com/logo-challenge/',
    picture1: './assets/img/logo-challenge-screens.png',
    picture2: './assets/img/logo-challenge-gif.gif',
    picture3: '',
    picture4: '',
  },

  {
    id: 6,
    name: 'Sixtines',
    coverPicture: './assets/img/sixtines-cover.jpg',
    deliverables: ['Identification system for Sales & Customers',
    'Unpaid invoices list',
      'Registrering new customer by sale',
      'Create new order',
      'Resume of order',
      'Mail confirmation',
      'Admin menu (admin)',
      'Add new product (admin)',
      'Stock Management (admin)'
    ],
    toolsSkills: ['UX/UI skills',
      'Front-end skills',
      'Figma',
      'Angular',
      'Agile (scrum) environement',
      '',
      '',''],
    myPosition: 'Junior front-end developer in a team of junior front-end',
    duration: '1 month (6 months formation of Full Stack Developer at WildeCodeSchool)',
    overviewText: 'During my formation at the WildCodeSchool, with my team, we have the mission to create the B2B website of the Belgium brand Sixitiens. ',
    subTitle1: 'The demand of the client',
    subTitle1Text: 'Create a B2B website to allow to manage the sales & customers',
    subTitle2: 'The solution',
    subTitle2Text: 'The solution was to create an Angular platforme with an authotification system and a Mysql database.',
    tasksTitleSection: 'STEPS',
    tasksTitleSectionText: 'During all the creation of the platfom, we met the client at each iteration to present or work and let the client be update with our work.',
    tasksSubTitle1: 'SQL database',
    tasksSubTitle1Text: ' We started with a first meeting with the lcient ot know what are they expecatations. After knowing, we start first with the creation of the database. We use MySQL Workbench to create the database. ',
    tasksSubTitle2: 'Mockups and  Integration',
    tasksSubTitle2Text: 'We use Figma to create the mock-up and to present to the client  ',
    tasksSubTitle3: '',
    tasksSubTitle3Text: '',
    linkProject: '',
    picture1: './assets/img/sixtines-mysql.jpg',
    picture2: './assets/img/sixtines-gif.gif',
    picture3: '',
    picture4: '',
  },
  {
    id: 7,
    name: 'Feelm',
    coverPicture: './assets/img/feelm-cover.jpg',
    deliverables: ['Angular website ',
      'Mobile version',
      'UX/UI',
      'Back-end', '', '', '', '', ''],
    toolsSkills: ['UX/UI skills',
      'Front-end skills',
      'Adobe PS',
      'Angular',
      'Agile (scrum) environement',
      '',
      '',
      ''],
    myPosition: 'Junior front-end developer in a team of junior front-end ',
    duration: '1 month(6 months formation of Full Stack Developer at WildeCodeSchool) ',
    overviewText: 'Feelm let you find the mvie which matched with your feelings. After my bachelor and an experienced as manual Testor, I decided to improve and update my skills in development to find a job i what I always lke. I followed 6 months courses in Angular at WildeCoSchool. There, We did different project FEELM it is one of them. I proposed the subject of the project and I occupied the front-end and design part during the project. ',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'TASKS',
    tasksTitleSectionText: '',
    tasksSubTitle1: 'API integration',
    tasksSubTitle1Text: 'We use the IMDB api as the database. ',
    tasksSubTitle2: 'Link the feelings with the movie',
    tasksSubTitle2Text: 'With the team, we choose to link the categories with feelings.',
    tasksSubTitle3: '',
    tasksSubTitle3Text: '',
    linkProject: 'https://github.com/Antssp1/feelm/',
    picture1: './assets/img/feelm-screens.png',
    picture2: './assets/img/feelm-gif.gif',
    picture3: '',
    picture4: '',
  },
  {
    id: 8,
    name: 'Media Animation',
    coverPicture: './assets/img/media-animation-cover.jpg',
    deliverables: [' AMOS: responsive website',
      ' BRICKS: visual communication',
      ' La Semaine Numérique: responsive newsletter',
      ' A film ouvert: press communication and newsletter', 
      ' ÖZGE: integration of wordpress theme', 
      ' Espace temps: responsive version', 
      ' autonomia.org: creation of icons', 
      ' hamsi: creation of the responsive version', 
      ' ...'],
    toolsSkills: ['Webdesigner',
      ' Integration skills',
      ' Adobe PS + AI',
      ' Bootstrap',
      ' Wordpress',
      ' HTML5 / CSS3',
      ' Optimisation of the HTML for the SEO',
      ' SPIP',],
    myPosition: 'Junior webdesigner',
    duration: '3 months (2017)',
    overviewText:'At Media ANIMATION, I met different clients and participatedt/created/collaborated in different projects.'+
    'The main project that I was participatetd was the refont of the AMOS website.'+ 
    'But I alos, redesigned, created/integrated mini websites, banners, responsive newsletters in HTML and CSS. I used WordPress to integrate some themes and created child themes to improve the CSS, recreate a icon library forautonomia.org, ...',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'PROJECTS',
    tasksTitleSectionText: 'In this section, I will present shrotly how I processed to create the AMOS website but also some newsletters and wordpress projects.',
    tasksSubTitle1: 'AMOS PROJECT',
    tasksSubTitle1Text: 'The assignment was to redesign a responsive website.'+
    'The AMOS non-profit organization in Schaerbeek, one of the agency´s clients, noticed that their site aimed at young people'+
    'did not attract them. They therefore decided to call on the agency and change their strategy of'+
    'communication, with a site targeting institutions and using their Facebook page for young people.'+
    'My position in this project was to proposed and integrated the design of the website. I worked with a graphit who created the logo. ',
    tasksSubTitle2: 'RESPONSIVE NEWSLETTERS',
    tasksSubTitle2Text: 'During my internship, I create some responsive newsletter. I used Photoshop and following graphic chart for the creation.'+ 
    'I integrated the newsletter with html. And test them on different clients.',
    tasksSubTitle3: 'WORDPRESS PROJECTS ',
    tasksSubTitle3Text: 'I worked on the OZGE site. I chose and integrated the wordpress template for the website.'+
    'I create the child theme and worked in collaboration with the content responsible on the website to integrate it.',
    linkProject: 'https://media-animation.be/',
    picture1: './assets/img/media-animation-amos.jpg',
    picture2: './assets/img/media-animation-newsletter.jpg',
    picture3: './assets/img/media-animation-wordpress.jpg',
    picture4: '',
  },
  {
    id: 9,
    name: 'RTL Belgium',
    coverPicture: './assets/img/rtl-cover.jpg',
    deliverables: ['Timeline responsive',
      ' Splash page',
      ' Newsletter responsive ',
      ' Benchmarking', 
      ' Mockup ', 
      ' Prototype ', '', '', ''],
    toolsSkills: ['Webdesigner',
      ' Adobe PS + AI',
      ' Fireworks',
      ' Benchemarking',
      ' Responsive',
      ' HTML',
      ' CSS',
      ' Dreamwaever',],
    myPosition: 'Webdesigner junior',
    duration: '3 months (2016)',
    overviewText: 'At RTL Belgium, I worked in divers elements as home page with splash page, newsletter, mobile, radio website RTL, timeline',
    subTitle1: '',
    subTitle1Text: '',
    subTitle2: '',
    subTitle2Text: '',
    tasksTitleSection: 'TASKS',
    tasksTitleSectionText: 'Here I share some works that I delivared during this internship',
    tasksSubTitle1: 'Newsletter',
    tasksSubTitle1Text: 'One of my task was to proposed the mobile version of the newsletter',
    tasksSubTitle2: 'Mocku-ups and prototype html',
    tasksSubTitle2Text: ' I also delevered some design propositions for the audio show BEL RTL and a timeline',
    tasksSubTitle3: 'Integration Timeline',
    tasksSubTitle3Text: 'I integrated in HTML5 and CSS3 the responsive timeline.',
    linkProject: 'https://www.rtl.be',
    picture1: './assets/img/rtl-newsletter.jpg',
    picture2: './assets/img/rtl-mockups.jpg',
    picture3: './assets/img/rtl-timeline.jpg',
    picture4: '',
  },

];